version = 0.1

[default.deploy.parameters]
stack_name = "sportsnet-poc2"
resolve_s3 = true
s3_prefix = "sportsnet-poc2"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "ap-northeast-1"
